<<<<<<< HEAD
version: "3.8"

services:
  zookeeper-node1:
    container_name: zookeeper-node1
    hostname: zookeeper-node1
    image: bitnami/zookeeper:3.6.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node1
    ports:
      - 21811:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zookeeper-node1:2888:3888,zookeeper-node2:2888:3888,zookeeper-node3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok

  zookeeper-node2:
    container_name: zookeeper-node2
    hostname: zookeeper-node2
    image: bitnami/zookeeper:3.6.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node2
    ports:
      - 21812:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-node1:2888:3888,zookeeper-node2:2888:3888,zookeeper-node3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok

  zookeeper-node3:
    container_name: zookeeper-node3
    hostname: zookeeper-node3
    image: bitnami/zookeeper:3.6.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node3
    ports:
      - 21813:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-node1:2888:3888,zookeeper-node2:2888:3888,zookeeper-node3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok

  zookeeper-navigator:
    container_name: zookeeper-navigator
    image: elkozmon/zoonavigator
    deploy:
      mode: global
    environment:
      HTTP_PORT: 9090
    ports:
      - 9090:9090

  solr-node1:
    hostname: solr-node1
    image: solr:8.7.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node1
    ports:
     - 8981:8983
    environment:
      - SOLR_PORT=8981
      - ZK_HOST=zookeeper-node1:2181,zookeeper-node2:2181,zookeeper-node3:2181
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
      - zookeeper-node3

  solr-node2:
    hostname: solr-node2
    image: solr:8.7.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node2
    ports:
     - 8982:8983
    environment:
      - SOLR_PORT=8982
      - ZK_HOST=zookeeper-node1:2181,zookeeper-node2:2181,zookeeper-node3:2181
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
      - zookeeper-node3

  solr-node3:
    hostname: solr-node3
    image: solr:8.7.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node3
    ports:
     - 8983:8983
    environment:
      - SOLR_PORT=8983
      - ZK_HOST=zookeeper-node1:2181,zookeeper-node2:2181,zookeeper-node3:2181
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
      - zookeeper-node3
=======
version: "3.8"

services:
  zookeeper-node1:
    container_name: zookeeper-node1
    hostname: zookeeper-node1
    image: bitnami/zookeeper:3.6.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node1
    ports:
      - 21811:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zookeeper-node1:2888:3888,zookeeper-node2:2888:3888,zookeeper-node3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok

  zookeeper-node2:
    container_name: zookeeper-node2
    hostname: zookeeper-node2
    image: bitnami/zookeeper:3.6.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node2
    ports:
      - 21812:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-node1:2888:3888,zookeeper-node2:2888:3888,zookeeper-node3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok

  zookeeper-node3:
    container_name: zookeeper-node3
    hostname: zookeeper-node3
    image: bitnami/zookeeper:3.6.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node3
    ports:
      - 21813:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-node1:2888:3888,zookeeper-node2:2888:3888,zookeeper-node3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok

  zookeeper-navigator:
    container_name: zookeeper-navigator
    image: elkozmon/zoonavigator
    deploy:
      mode: global
    environment:
      HTTP_PORT: 9090
    ports:
      - 9090:9090

  solr-node1:
    hostname: solr-node1
    image: solr:8.7.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node1
    ports:
     - 8981:8983
    environment:
      - SOLR_PORT=8981
      - ZK_HOST=zookeeper-node1:2181,zookeeper-node2:2181,zookeeper-node3:2181
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
      - zookeeper-node3

  solr-node2:
    hostname: solr-node2
    image: solr:8.7.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node2
    ports:
     - 8982:8983
    environment:
      - SOLR_PORT=8982
      - ZK_HOST=zookeeper-node1:2181,zookeeper-node2:2181,zookeeper-node3:2181
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
      - zookeeper-node3

  solr-node3:
    hostname: solr-node3
    image: solr:8.7.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dc == node3
    ports:
     - 8983:8983
    environment:
      - SOLR_PORT=8983
      - ZK_HOST=zookeeper-node1:2181,zookeeper-node2:2181,zookeeper-node3:2181
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
      - zookeeper-node3
>>>>>>> df1796f9e88a497c22889bda56b96e502167a7f6
